import type { JiraBuiltInFieldId, JiraEnumRemap, JiraFieldMappingSettings, JiraIssue, JiraValueSource, JiraValueSourceMode, TaskCreationData, UserMappedField } from './types';

const UNSAFE = new Set(['__proto__', 'prototype', 'constructor']);
const MODES = new Set<JiraValueSourceMode>(['path', 'template', 'fixed', 'off']);
const LIST_FIELDS = new Set<JiraBuiltInFieldId>(['tags', 'projects', 'contexts']);
const FIELDS: JiraBuiltInFieldId[] = ['id', 'title', 'details', 'status', 'priority', 'due', 'scheduled', 'timeEstimate', 'dateCreated', 'dateModified', 'completedDate', 'recurrence', 'tags', 'projects', 'contexts'];
export const JIRA_MAPPING_TARGETS = FIELDS.map((id) => ({ id, kind: LIST_FIELDS.has(id) ? 'list' as const : id === 'timeEstimate' ? 'number' as const : ['due', 'scheduled', 'dateCreated', 'dateModified', 'completedDate'].includes(id) ? 'date' as const : 'text' as const }));
export interface JiraMappingPreviewEntry { id: string; label: string; status: 'value' | 'empty' | 'missing' | 'invalid'; value?: unknown }

export function createDefaultJiraMappingSettings(): JiraFieldMappingSettings {
	return { version: 1, fields: {
		id: [{ mode: 'path', value: 'key' }], title: [{ mode: 'template', value: '$key $fields.summary' }], details: [{ mode: 'path', value: 'fields.description' }],
		status: [{ mode: 'path', value: 'fields.status.name' }], priority: [{ mode: 'path', value: 'fields.priority.name' }], due: [{ mode: 'path', value: 'fields.duedate' }],
		scheduled: [{ mode: 'off', value: '' }], timeEstimate: [{ mode: 'path', value: 'fields.timeestimate' }], dateCreated: [{ mode: 'path', value: 'fields.created' }],
		dateModified: [{ mode: 'path', value: 'fields.updated' }], completedDate: [{ mode: 'path', value: 'fields.resolutiondate' }], recurrence: [{ mode: 'off', value: '' }],
		tags: [{ mode: 'path', value: 'fields.labels' }], projects: [], contexts: [],
	}, userFields: {}, enumRemaps: { status: [], priority: [], contexts: [] } };
}
function isRecord(value: unknown): value is Record<string, unknown> { return !!value && typeof value === 'object' && !Array.isArray(value); }
function own(value: unknown, key: string): unknown { return isRecord(value) && !UNSAFE.has(key) && Object.prototype.hasOwnProperty.call(value, key) ? value[key] : undefined; }
export function getJiraValueByPath(root: unknown, path: string): unknown {
	const parts = path.trim().split('.').map((part) => { const match = /^([A-Za-z0-9_]+)(?:\[(\d*)\])?$/.exec(part); const key = match?.[1]; if (!match || !key || UNSAFE.has(key)) return null; return { key, project: match[2] === '', index: match[2] && match[2] !== '' ? Number(match[2]) : undefined }; });
	if (!parts.length || parts.some((part) => !part)) return undefined; let values: unknown[] = [root]; let projected = false;
	for (const parsed of parts) { const part = parsed!; const next: unknown[] = []; for (const value of values) { const property = own(value, part.key); if (part.project && Array.isArray(property)) { next.push(...(property as unknown[])); projected = true; } else if (part.index !== undefined && Array.isArray(property) && part.index < property.length) next.push(property[part.index]); else if (!part.project && part.index === undefined && property !== undefined) next.push(property); } values = next; if (!values.length) return undefined; }
	return projected || values.length > 1 ? values.flat(Infinity) : values[0];
}
function flatten(value: unknown): string[] { const primitive = (item: unknown): item is string | number | boolean => typeof item === 'string' || typeof item === 'number' || typeof item === 'boolean'; return [...new Set((Array.isArray(value) ? (value as unknown[]).flat(Infinity) : [value]).filter(primitive).map((item) => String(item).trim()).filter(Boolean))]; }
export function jiraRichTextToMarkdown(value: unknown): string | undefined {
	if (typeof value === 'string') return value.trim() || undefined; if (!isRecord(value)) return undefined; const out: string[] = [];
	const visit = (node: unknown): void => { if (!isRecord(node)) return; if (typeof node.text === 'string') out.push(node.text); if (Array.isArray(node.content)) { node.content.forEach(visit); if (node.type === 'paragraph' || node.type === 'heading') out.push('\n'); } }; visit(value); return out.join('').trim() || undefined;
}
function stringify(value: unknown): string { if (Array.isArray(value)) return flatten(value).join(', '); if (value == null) return ''; if (typeof value === 'object') return jiraRichTextToMarkdown(value) ?? ''; if (typeof value === 'string') return value; if (typeof value === 'number' || typeof value === 'boolean') return String(value); return ''; }
export function renderJiraTemplate(template: string, issue: JiraIssue): string { return template.replace(/\$([A-Za-z0-9_]+(?:\[(?:\d*)\])?(?:\.[A-Za-z0-9_]+(?:\[(?:\d*)\])?)*)/g, (_match, path: string) => stringify(getJiraValueByPath(issue, path === 'summary' ? 'fields.summary' : path === 'description' ? 'fields.description' : path))).replace(/\\n/g, '\n').trim(); }
function readSource(source: JiraValueSource, issue: JiraIssue): unknown { if (source.mode === 'off') return undefined; if (source.mode === 'fixed') return source.value; if (source.mode === 'template') return renderJiraTemplate(source.value, issue); return getJiraValueByPath(issue, source.value); }
function first(sources: JiraValueSource[], issue: JiraIssue): unknown { for (const source of sources) { const value = readSource(source, issue); if (value !== undefined && value !== null && value !== '') return value; } return undefined; }
function text(value: unknown): string | undefined { if (typeof value === 'object' && value !== null) return jiraRichTextToMarkdown(value); if (!['string', 'number', 'boolean'].includes(typeof value)) return undefined; return String(value).trim() || undefined; }
function number(value: unknown): number | undefined { const parsed = typeof value === 'number' ? value : Number(text(value)); return Number.isFinite(parsed) ? parsed : undefined; }
function date(value: unknown): string | undefined { const parsed = text(value); return parsed && !Number.isNaN(Date.parse(parsed)) ? parsed : undefined; }
function boolean(value: unknown): boolean | undefined { if (typeof value === 'boolean') return value; const parsed = text(value)?.toLowerCase(); return ['true', 'yes', '1'].includes(parsed ?? '') ? true : ['false', 'no', '0'].includes(parsed ?? '') ? false : undefined; }
function remap(value: string | undefined, maps: JiraEnumRemap[]): string | undefined { if (!value) return undefined; return maps.find((map) => map.jiraValues.some((incoming) => incoming.toLowerCase() === value.toLowerCase()))?.taskValue || value; }
export function buildJiraIssueBacklink(issue: JiraIssue): string { return `JIRA:${issue.key}`; }
export function prependJiraIssueBacklink(details: string | undefined, issue: JiraIssue): string { const existing = details?.trim() ?? ''; const key = issue.key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); if (new RegExp(`\\bJIRA\\s*:\\s*${key}\\b`, 'i').test(existing)) return existing; return existing ? `${buildJiraIssueBacklink(issue)}\n\n${existing}` : buildJiraIssueBacklink(issue); }
function normalizeSource(value: unknown): JiraValueSource | null { return isRecord(value) && MODES.has(value.mode as JiraValueSourceMode) ? { mode: value.mode as JiraValueSourceMode, value: typeof value.value === 'string' ? value.value : '' } : null; }
function normalizeSources(value: unknown, fallback: JiraValueSource[]): JiraValueSource[] { if (!Array.isArray(value)) return fallback.map((source) => ({ ...source })); const sources = value.map(normalizeSource).filter((source): source is JiraValueSource => !!source); return value.length && !sources.length ? fallback.map((source) => ({ ...source })) : sources; }
function normalizeRemaps(value: unknown): JiraEnumRemap[] { return Array.isArray(value) ? value.filter(isRecord).map((entry) => ({ taskValue: typeof entry.taskValue === 'string' ? entry.taskValue.trim() : '', jiraValues: flatten(entry.jiraValues) })).filter((entry) => entry.taskValue && entry.jiraValues.length) : []; }
export function normalizeJiraMappingSettings(value: unknown): JiraFieldMappingSettings {
	const defaults = createDefaultJiraMappingSettings(); if (!isRecord(value)) return defaults; const fieldSource = isRecord(value.fields) ? value.fields : value; const fields: JiraFieldMappingSettings['fields'] = {};
	for (const field of FIELDS) { const raw = isRecord(value.fields) ? fieldSource[field] : fieldSource[field] === undefined ? undefined : Array.isArray(fieldSource[field]) ? fieldSource[field] : [fieldSource[field]]; fields[field] = normalizeSources(raw, defaults.fields[field] ?? []); }
	const rawUsers = isRecord(value.userFields) ? value.userFields : {}; const userFields: Record<string, JiraValueSource[]> = {}; for (const [id, sources] of Object.entries(rawUsers)) if (id && !UNSAFE.has(id)) userFields[id] = normalizeSources(sources, []);
	const maps = isRecord(value.enumRemaps) ? value.enumRemaps : value; return { version: 1, fields, userFields, enumRemaps: { status: normalizeRemaps(maps.status ?? value.statusMap), priority: normalizeRemaps(maps.priority ?? value.priorityMap), contexts: normalizeRemaps(maps.contexts ?? value.contextsMap) } };
}
export function mapJiraIssueWithSettings(issue: JiraIssue, settings: JiraFieldMappingSettings, userFields: readonly UserMappedField[]): TaskCreationData {
	const config = normalizeJiraMappingSettings(settings); const read = (field: JiraBuiltInFieldId): unknown => LIST_FIELDS.has(field) ? (config.fields[field] ?? []).flatMap((source) => flatten(readSource(source, issue))) : first(config.fields[field] ?? [], issue);
	const mappedDetails = jiraRichTextToMarkdown(read('details')) ?? text(read('details')); const estimate = number(read('timeEstimate'));
	const output: TaskCreationData = { creationContext: 'import', title: text(read('title')) || `${issue.key.trim()} ${issue.fields.summary.trim()}`, details: prependJiraIssueBacklink(mappedDetails, issue) };
	Object.assign(output, { id: text(read('id')), status: remap(text(read('status')), config.enumRemaps.status), priority: remap(text(read('priority'))?.toLowerCase(), config.enumRemaps.priority), due: date(read('due')), scheduled: date(read('scheduled')), timeEstimate: estimate !== undefined && estimate >= 0 ? Math.floor(estimate / 60) : undefined, dateCreated: date(read('dateCreated')), dateModified: date(read('dateModified')), completedDate: date(read('completedDate')), recurrence: text(read('recurrence')) });
	const tags = flatten(read('tags')); const projects = flatten(read('projects')); const contexts = flatten(read('contexts')).map((value) => remap(value, config.enumRemaps.contexts) ?? value); if (tags.length) output.tags = tags; if (projects.length) output.projects = projects; if (contexts.length) output.contexts = contexts;
	const custom: Record<string, unknown> = {}; for (const field of userFields) { const sources = config.userFields[field.id] ?? []; const raw = field.type === 'list' ? sources.flatMap((source) => flatten(readSource(source, issue))) : first(sources, issue); const value = field.type === 'number' ? number(raw) : field.type === 'date' ? date(raw) : field.type === 'boolean' ? boolean(raw) : field.type === 'list' ? flatten(raw) : text(raw); if (value !== undefined && (!Array.isArray(value) || value.length)) custom[field.key] = value; } if (Object.keys(custom).length) output.customFrontmatter = custom; return output;
}
export function buildJiraMappingPreview(issue: JiraIssue, settings: JiraFieldMappingSettings, userFields: readonly UserMappedField[]): JiraMappingPreviewEntry[] {
	const config = normalizeJiraMappingSettings(settings); const mapped = mapJiraIssueWithSettings(issue, config, userFields) as unknown as Record<string, unknown>; const entries: JiraMappingPreviewEntry[] = [];
	for (const target of JIRA_MAPPING_TARGETS) { const resolved = (config.fields[target.id] ?? []).map((source) => readSource(source, issue)).filter((value) => value !== undefined && value !== null && value !== ''); const value = mapped[target.id]; entries.push(value !== undefined ? { id: target.id, label: target.id, status: Array.isArray(value) && !value.length ? 'empty' : 'value', value } : target.kind === 'list' && resolved.length ? { id: target.id, label: target.id, status: 'empty', value: [] } : { id: target.id, label: target.id, status: resolved.length ? 'invalid' : 'missing' }); }
	for (const field of userFields) { const resolved = (config.userFields[field.id] ?? []).map((source) => readSource(source, issue)).filter((value) => value !== undefined && value !== null && value !== ''); const value = (mapped.customFrontmatter as Record<string, unknown> | undefined)?.[field.key]; entries.push(value !== undefined ? { id: field.id, label: field.displayName, status: Array.isArray(value) && !value.length ? 'empty' : 'value', value } : field.type === 'list' && resolved.length ? { id: field.id, label: field.displayName, status: 'empty', value: [] } : { id: field.id, label: field.displayName, status: resolved.length ? 'invalid' : 'missing' }); }
	return entries;
}
