import { describe, expect, it } from 'vitest';
import { buildJiraMappingPreview, createDefaultJiraMappingSettings, getJiraValueByPath, mapJiraIssueWithSettings, normalizeJiraMappingSettings, prependJiraIssueBacklink, renderJiraTemplate } from '../src/jira/JiraFieldMapping';
import type { JiraIssue } from '../src/jira/types';
const issue: JiraIssue = { key: 'MAGIC-17', fields: { summary: 'Audit inventory', description: 'Keep details.', status: { name: 'Doing' }, priority: { name: 'Major' }, components: [{ name: 'Lab' }, { name: 'Vault' }], labels: ['magic'], timeestimate: 3600, custom: '8' } };
describe('Jira mapping', () => {
	it('resolves safe paths and rejects inherited or unsafe paths', () => { expect(getJiraValueByPath(issue, 'fields.components[].name')).toEqual(['Lab', 'Vault']); expect(getJiraValueByPath(issue, 'fields.__proto__.x')).toBeUndefined(); const inherited = Object.create({ secret: 1 }) as Record<string, unknown>; expect(getJiraValueByPath(inherited, 'secret')).toBeUndefined(); });
	it('renders templates and missing values', () => { expect(renderJiraTemplate('$key $summary\\n$fields.missing', issue)).toBe('MAGIC-17 Audit inventory'); });
	it('maps lists, remaps enums, coerces user fields, and converts seconds to minutes', () => { const settings = createDefaultJiraMappingSettings(); settings.fields.contexts = [{ mode: 'path', value: 'fields.components[].name' }, { mode: 'fixed', value: 'Lab' }]; settings.enumRemaps.status = [{ taskValue: 'in-progress', jiraValues: ['doing'] }]; settings.userFields.points = [{ mode: 'path', value: 'fields.custom' }]; const mapped = mapJiraIssueWithSettings(issue, settings, [{ id: 'points', displayName: 'Points', key: 'points', type: 'number' }]); expect(mapped).toMatchObject({ status: 'in-progress', contexts: ['Lab', 'Vault'], timeEstimate: 60, customFrontmatter: { points: 8 } }); });
	it('preserves details and prevents duplicate Jira macros', () => { const once = prependJiraIssueBacklink('Keep details.', issue); expect(once).toBe('JIRA:MAGIC-17\n\nKeep details.'); expect(prependJiraIssueBacklink(once, issue)).toBe(once); });
	it('migrates legacy settings and reports invalid previews', () => { const settings = normalizeJiraMappingSettings({ title: { mode: 'template', value: '$key: $summary' }, statusMap: [{ taskValue: 'done', jiraValues: ['Closed'] }] }); expect(settings.fields.title).toEqual([{ mode: 'template', value: '$key: $summary' }]); settings.fields.due = [{ mode: 'fixed', value: 'bad-date' }]; expect(buildJiraMappingPreview(issue, settings, [])).toContainEqual(expect.objectContaining({ id: 'due', status: 'invalid' })); });
});
